# Generated by Django 3.1.7 on 2021-04-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_link',
            field=models.URLField(default='https://nitreo.com/img/igDefaultProfilePic.png'),
        ),
    ]
