# Generated by Django 3.1.7 on 2021-04-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0002_user_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image_link',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
